

Avatar
TiyaGandhi
Access all features with our Premium subscription!
myLists
My Lists
notebook
Notebook
progress
Progress
points
Points
Problems
Discuss
Contest
Interview
Store
Try New Features
Orders
My Playgrounds
Settings
Appearance
Sign Out
389. Find the Difference
Easy
Topics
premium lock icon
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 
Accepted
1,163,226/1.9M
Acceptance Rate
60.6%
C++




1
2
3
4
5
6
⌄
⌄
class Solution {
public:
    char findTheDifference(string s, string t) {
        
    }
};
Saved
Testcase
1
2
3
4
"abcd"
"abcde"
""
"y"
2/8 testcases
Line 1
Case 1: s
Copyright © 2026 LeetCode. All rights reserved.

5.6K


159
Search questions


